# -*- coding: utf-8 -*-
"""12_manejo_cadenas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCFmBb17LMRZaG1RWmpY-Epetmc6-OGg

# Manejo de cadenas de caracteres
"""

cadena = 'En un lugar de La Mancha'

"""Método **replace**: reemplazar subcadenas"""

resultado = cadena.replace('a','@')
print(resultado)

"""Método **swapcase**: invierte mayúsculas y minúsculas

---


"""

resultado = cadena.swapcase()
print(resultado)

"""Método **capitalize**: Convierte la primera letra del str en mayúsculas y el resto en minúsculas"""

resultado = cadena.capitalize()
print(resultado)

"""Método **title**: Convierte la primera letra de cada palatra del str en mayúsculas y el resto en minúsculas"""

resultado = cadena.title()
print(resultado)

"""Método **count**: cuenta el número de veces que aparece una subcadena un texto. Si no encuentra la subcadena devuelve 0."""

resultado = cadena.count(' ')
print(resultado)

"""Método **index**: obtiene la posición de una subcadena en un str. Si no encuentra la subcadena provoca un errro de ejecución del tipo ValueError."""

resultado = cadena.index('an')
print(resultado)

"""Método **startswith**: indica si empieza o no por una determina subcadena."""

resultado = cadena.startswith('En un')
print(resultado)
resultado = cadena.startswith('Hace mucho tiempo...')
print(resultado)

"""Método **endswith**: indica si la cadena termina o no por una determinada subcadena."""

resultado = cadena.endswith('hola, mi nombre es José')
print(resultado)
resultado = cadena.endswith('Mancha')
print(resultado)

"""Médodo **find**: busca la primera aparición de una subcadena una cadena. Devuelve la posición donde la encuentra o -1 si no."""

resultado = cadena.find('an')
print(resultado)

"""Método **isdecimal**: verifica si todos los dígitos son decimales (devuelve True o False)"""

es_decimal = cadena.isdecimal()
print(es_decimal) # False
es_decimal = '12345'.isdecimal()
print(es_decimal) # True
es_decimal = '123.45'.isdecimal()
print(es_decimal) # False

"""Métodos **isdigit** y **isnumeric**: isdigit comprueba si contiene dígitos numéricos e isnumeric si contiene expresiones numéricas"""

texto_1 = "1234"
texto_2 = "12r4"
texto_3 = "0b10101"
texto_4 = "10.3"
print(texto_1.isdigit()) # True
print(texto_2.isdigit()) # False
print(texto_3.isdigit()) # False
print(texto_4.isdigit()) # False
print(texto_1.isnumeric()) # True
print(texto_2.isnumeric()) # False
print(texto_3.isnumeric()) # False
print(texto_4.isnumeric()) # False

"""Métodos **islower**, **isupper** y **isspace**: comprueba si una cadena está completamente escrita en minúsculas, mayúsculas o contiene únicamente espacios. Los métodos islower e isupper sólo afectan a los caracteres alfabéticos."""

print(cadena.islower()) # False
print(cadena.isupper()) # False
print(cadena.isspace()) # False
print('soy una cadena'.islower()) # True
print('SOY UNA CADENA'.isupper()) # True
print('         '.isspace()) # True

"""Métodos **upper** y **lower**: devuelve una copia de la cadena con los caracteres alfabéticos convertidos a mayúsculas y minúsculas respectivamente."""

print(cadena.upper())
print(cadena.lower())